backend:
  name: github
  repo: cmcintyre416/cm-portfolio-master

media_folder: static/assets
public_folder: assets

collections:
  - name: navLinks
    label: Nav Links
    folder: navLinks
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
  - name: projects
    label: Projects
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }